Do not redefine `bool`, `true` and `false` keywords
libsndfile/libsndfile pull request #1055
Opened 2024-12-17 09:47 UTC by fabiangreffrath

Fixes #1049

2024-12-17 21:57 UTC, SoapGentoo requested changes

2024-12-17 21:57 UTC, SoapGentoo commented on src/ALAC/alac_codec.h
> +#endif
nix this entire lot and just include `<stdbool.h>` in the headers/files that need it. It's 2024, if you dont have a C99 compiler, I'm sorry for you.

2024-12-18 17:09 UTC, SoapGentoo approved these changes

2025-02-06 10:59 UTC, fabiangreffrath commented
@SoapGentoo will you merge this?

2025-02-06 11:02 UTC, merged