Fix signed integer overflow
libsndfile/libsndfile pull request #818
Opened 2022-03-31 14:02 UTC by shao-hua-li

related to https://github.com/libsndfile/libsndfile/issues/785

2022-04-01 08:45 UTC, evpobr commented
@shao-hua-li ?

2022-04-01 08:47 UTC, evpobr requested changes

2022-04-01 08:47 UTC, evpobr commented on src/gsm610.c
> +		psf->sf.frames = (long)pgsm610->samplesperblock * pgsm610->blocks ;
```suggestion
		psf->sf.frames = (sf_count_t) pgsm610->samplesperblock * pgsm610->blocks ;
```

2022-04-01 09:14 UTC, shao-hua-li commented on src/gsm610.c
> +		psf->sf.frames = (long)pgsm610->samplesperblock * pgsm610->blocks ;
Yes, I agree with you.

2022-04-01 09:16 UTC, evpobr approved these changes

2022-04-01 09:17 UTC, evpobr commented
Okay, let's wait a couple of days so that the rest of the maintainers have time to see it.

2022-04-04 20:02 UTC, arthurt approved these changes
Regardless of #785, this change does have merit.

2022-04-06 05:07 UTC, merged