Fixing signed integer overflow in g72x.c
libsndfile/libsndfile pull request #842
Opened 2022-05-30 08:08 UTC by shao-hua-li

Fixing signed integer overflow as reported in https://github.com/libsndfile/libsndfile/issues/757 . A similar fix was applied before https://github.com/libsndfile/libsndfile/pull/818

2022-05-30 08:17 UTC, evpobr requested changes
Change title to "Fix signed integer overflow in g72x.c" please.

2022-05-31 06:26 UTC, arthurt approved these changes

2022-05-31 08:09 UTC, evpobr approved these changes

2022-05-31 08:10 UTC, merged

2022-05-31 08:10 UTC, evpobr commented
Thaks @shao-hua-li !